# Generated by Django 5.1 on 2024-09-24 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='eudamed_data',
            fields=[
                ('basic_udi', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('primary_di', models.CharField(max_length=255)),
                ('uuid', models.CharField(max_length=255)),
                ('ulid', models.CharField(max_length=255)),
                ('basic_udi_di_data_ulid', models.CharField(max_length=255)),
                ('risk_class', models.CharField(blank=True, max_length=50, null=True)),
                ('device_name', models.CharField(max_length=255)),
                ('manufacturer_name', models.CharField(max_length=255)),
                ('manufacturer_srn', models.CharField(blank=True, max_length=255, null=True)),
                ('device_status_type', models.CharField(blank=True, max_length=255, null=True)),
                ('manufacturer_status', models.CharField(blank=True, max_length=255, null=True)),
                ('latest_version', models.CharField(blank=True, max_length=50, null=True)),
                ('version_number', models.CharField(blank=True, max_length=50, null=True)),
                ('reference', models.CharField(blank=True, max_length=255, null=True)),
                ('basic_udi_data_version_number', models.CharField(blank=True, max_length=50, null=True)),
                ('container_package_count', models.IntegerField(blank=True, null=True)),
                ('authorised_representative_srn', models.CharField(blank=True, max_length=255, null=True)),
                ('authorised_representative_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'eudamed_data',
            },
        ),
        migrations.CreateModel(
            name='fda_data',
            fields=[
                ('k_number', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('manufacturer_name', models.CharField(max_length=255)),
                ('contact', models.CharField(blank=True, max_length=255, null=True)),
                ('address1', models.CharField(blank=True, max_length=255, null=True)),
                ('address2', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('country_code', models.CharField(max_length=3)),
                ('zip_code', models.CharField(max_length=20)),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('date_received', models.DateField(blank=True, null=True)),
                ('decision_date', models.DateField(blank=True, null=True)),
                ('decision_description', models.TextField(blank=True, null=True)),
                ('product_code', models.CharField(max_length=50)),
                ('statement_or_summary', models.TextField(blank=True, null=True)),
                ('clearance_type', models.CharField(blank=True, max_length=50, null=True)),
                ('third_party_flag', models.BooleanField(default=False)),
                ('expedited_review_flag', models.BooleanField(default=False)),
                ('device_name', models.CharField(max_length=255)),
                ('url', models.URLField(blank=True, null=True)),
                ('device_description', models.TextField(blank=True, null=True)),
                ('medical_specialty_description', models.CharField(blank=True, max_length=255, null=True)),
                ('device_class', models.CharField(blank=True, max_length=50, null=True)),
                ('regulation_number', models.CharField(blank=True, max_length=50, null=True)),
                ('submission_type_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'fda_data',
            },
        ),
    ]
